[package]
name = "windows-amsi-provider-rust"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]

widestring = { version = "1.1.0" }
libc = { version = "0.2.154" }
com = { version = "0.6.0", features = ["production"] }
